services:
  - type: web
    name: online-cheating-protector
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.0
    healthCheckPath: /
