services:
  - type: web
    name: proctorai
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
    healthCheckPath: /
